### ISSUE TITLE
When trying the End to End test example, property test is passed while it is supposed to fail

### ISSUE THREAD

**Issue by BarrySauce** [crytic/building-secure-contracts#105]
I am referring to this tutorial: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/end-to-end-testing.md
I follow all the instructions in the tutorial, however, the test result I get is "passed", rather than "failed"

The test contract:

<img width="693" alt="Screenshot 2022-04-16 at 5 05 25 AM" src="https://user-images.githubusercontent.com/84897434/163632011-6ef3ef55-7203-4824-aec3-559cb3a4cb86.png">

The init file created by Etheno when running the unit test:

<img width="1353" alt="Screenshot 2022-04-16 at 5 05 57 AM" src="https://user-images.githubusercontent.com/84897434/163632061-78adce19-84ba-4629-94e1-63de29888b72.png">

The echidna config file:

<img width="251" alt="Screenshot 2022-04-16 at 5 06 15 AM" src="https://user-images.githubusercontent.com/84897434/163632102-3b71cbb9-a88a-499d-b952-981c1684596a.png">

Final result:

<img width="557" alt="Screenshot 2022-04-16 at 5 06 48 AM" src="https://user-images.githubusercontent.com/84897434/163632127-1c306a1f-d5c4-434e-904c-afa9c23d1d28.png">

**Comment by ggrieco-tob** [comment]
This works fine here. Your json file looks correct to me however, can you please try using the suggested echidna file?

```yaml
prefix: crytic_
initialize: init.json
multi-abi: true
cryticArgs: ['--truffle-build-directory', 'app/src/contracts/'] # needed by drizzle
```

Also please update to the latest Echidna release (2.0.1). I will still improve the tutorial with a few minor changes, so please take a look later just in case.

**Comment by BarrySauce** [comment]
> This works fine here. Your json file looks correct to me however, can you please try using the suggested echidna file?
> 
> ```yaml
> prefix: crytic_
> initialize: init.json
> multi-abi: true
> cryticArgs: ['--truffle-build-directory', 'app/src/contracts/'] # needed by drizzle
> ```
> 
> Also please update to the latest Echidna release (2.0.1). I will still improve the tutorial with a few minor changes, so please take a look later just in case.

@ggrieco-tob Sure, let me give it a try. Actually I am also referring to this post https://github.com/crytic/echidna/wiki/How-to-use-Echidna-with-multiple-contracts, Echidna can output correct result using the proxy method. The proxy contract I write is as follow:
<img width="639" alt="Screenshot 2022-05-09 at 3 35 22 PM" src="https://user-images.githubusercontent.com/84897434/167362401-faa19545-e2c4-4d8e-af9b-a96bc0438429.png">

**Comment by BarrySauce** [comment]
> This works fine here. Your json file looks correct to me however, can you please try using the suggested echidna file?
> 
> ```yaml
> prefix: crytic_
> initialize: init.json
> multi-abi: true
> cryticArgs: ['--truffle-build-directory', 'app/src/contracts/'] # needed by drizzle
> ```
> 
> Also please update to the latest Echidna release (2.0.1). I will still improve the tutorial with a few minor changes, so please take a look later just in case.

@ggrieco-tob And may I know what the 'cryticArgs' means in the config file, I enter the app/src/contracts directory and find out there are only json files of the compiled contracts.

**Comment by ggrieco-tob** [comment]
> And may I know what the 'cryticArgs' means in the config file, I enter the app/src/contracts directory and find out there are only json files of the compiled contracts.

`cryticArgs` are a list  of additional arguments to use in `crytic-compile` for the compilation of the contract to test. An up-to-date list of the echidna config options is available here: https://github.com/crytic/echidna/wiki/Config

**Comment by ggrieco-tob** [comment]
@elopez can you take a look and try to reproduce this issue in MacOS? (which seems to be used here).

**Comment by elopez** [comment]
Following the process [as of this version](https://github.com/crytic/building-secure-contracts/blob/50a3ca49ec40a20de4de415013b742bb050e3ab8/program-analysis/echidna/end-to-end-testing.md) of the document worked okay on my Mac, with a few caveats:

* I had to `npm i ganache-cli@6`, otherwise etheno would not play nice with ganache-cli v7.x
* I had to install etheno this way, otherwise I would end up with broken dependencies that would not let me run it:

```sh
python3 -m venv venv
venv/bin/pip3 install https://github.com/crytic/etheno/archive/refs/heads/master.zip 'eth-rlp<0.3.0'
```

@BarrySauce note that you're passing the `.sol` directly to echidna on your call -- you need to pass the project folder instead and let truffle handle the build of the E2E and other contracts. Give `./echidna-test drizzle-box/ --contract E2E --config echidna.yaml` a try and let us know if that helps!

**Comment by BarrySauce** [comment]
> Following the process [as of this version](https://github.com/crytic/building-secure-contracts/blob/50a3ca49ec40a20de4de415013b742bb050e3ab8/program-analysis/echidna/end-to-end-testing.md) of the document worked okay on my Mac, with a few caveats:
> 
> * I had to `npm i ganache-cli@6`, otherwise etheno would not play nice with ganache-cli v7.x
> * I had to install etheno this way, otherwise I would end up with broken dependencies that would not let me run it:
> 
> ```shell
> python3 -m venv venv
> venv/bin/pip3 install https://github.com/crytic/etheno/archive/refs/heads/master.zip 'eth-rlp<0.3.0'
> ```
> 
> @BarrySauce note that you're passing the `.sol` directly to echidna on your call -- you need to pass the project folder instead and let truffle handle the build of the E2E and other contracts. Give `./echidna-test drizzle-box/ --contract E2E --config echidna.yaml` a try and let us know if that helps!

@elopez I tried your command and it works! Thank you for your help, and thank @ggrieco-tob for your support. So in case of this kind of test using with Etheno, we cannot pass the specific E2E .sol file, instead we are supposed to pass the project folder and the contract 👍

**Comment by ggrieco-tob** [comment]
Thanks for opening the issue and help us to improve our documentation. I added a clarification in the tutorial to avoid this issue in the future: https://github.com/crytic/building-secure-contracts/commit/82bdc6950693ac2891ff609170bb93bb0e6
