### ISSUE TITLE
Create guidelines on how to read the yellow paper

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#121]
- What sections to focus
- What areas to master
- What questions readers should be able to answer

Etc...

**Comment by montyly** [comment]
@bohendo has https://github.com/bohendo/evm-notes that could be a good start

**Comment by glarregay-tob** [comment]
It is available [here](https://docs.google.com/document/d/1Tqh-GnAO3v15ia2DO_NaHucbdHfbE6RtrURPCYHiTNs/edit?usp=sharing). It was mostly notes I took while reading it, and some of those notes are still on paper. Never gave myself the time to finish typing them 😢 let me know if it's useful, or if you need help with this.
