### ISSUE TITLE
Create EIP forks for EVM-compatible chain

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#133]
This https://github.com/crytic/building-secure-contracts/blob/master/learn_evm/eips_forks.md, but for BSC/Avalanche, etc..

**Comment by suryansh-tob** [comment]
I've set this up for TRON.
- Avalanche hasn't set up improvement proposals as of now
- BSC has less documentation on implemented BEPs for earlier BSC releases, more difficult to document in detail but will add what I've gathered so far

Most EVM-compatible chains unfortunately don't have fleshed out improvement proposals. I'll work on adding a section for Celo.
