### ISSUE TITLE
Add a list with all Trail of Bits blogposts

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#144]
Over the years we wrote a lot of technical blogposts. We should list everything in a page to increase their visibility

**Comment by GrosQuildu** [comment]
@montyly where do you want the list? `learn_evm/blogposts.md` or in `Development guidelines`?
Blockchain only, or EVM/solidity only, or anything that is even remotely relevant to blockchains dev?

**Comment by montyly** [comment]
- Maybe `ressources/blogposts.md` or `ressources/tob_blogposts.md`
- All our blockchain related blogposts. I think we can also include the zk related stuff

It would be great to have one sentence per blogpost, and maybe categories? Like
```
## General
- NAME1. One sentence

## Upgradeability
- NAME1. One sentence

## Tooling
- NAME1. One sentence
- NAME2. One sentence

```

**Comment by GrosQuildu** [comment]
Solved by https://github.com/crytic/building-secure-contracts/pull/152
