### ISSUE TITLE
Fix AssertionFailure or AssertionFailed events in doc

### ISSUE THREAD

**Issue by cpecorari** [crytic/building-secure-contracts#163]
Hi,
Been implementing Echidna's with some old forked contracts in Solidity 0.5.16 (guess what ^^), so had to implement event failure, but it seems Echidna's documentation is not very well maintained, or at some point the event name has changed and documentation only partly ?

See here `AssertionFailure()` and `AssertionFailed()` events : 
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/testing-modes.md
See also here only `AssertionFailed()` is mentioned : 
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/assertion-checking.md

Would you clarify on this please ? 

Thanks !

**Comment by ggrieco-tob** [comment]
Fixed in https://github.com/crytic/building-secure-contracts/pull/166
