### ISSUE TITLE
Exercises echidna invalid urls

### ISSUE THREAD

**Issue by ahpaleus** [crytic/building-secure-contracts#200]
Hints in exercise 8, mentioned [here](https://github.com/crytic/building-secure-contracts/blame/master/program-analysis/echidna/Exercise-8.md#L42-L43), do not exist.

> - A template is provided in [contracts/the-rewarder/EchidnaRewarder.sol](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/contracts/the-rewarder/EchidnaRewarder.sol)
> - A config file is provided in [the-rewarder.yaml](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/the-rewarder.yaml)

**Comment by ggrieco-tob** [comment]
@glarregay-tob can you fix this?

**Comment by ahpaleus** [comment]
There are a couple more invalid URLs. Maybe it would be beneficial to use this GitHub Action to check for broken links: https://github.com/gaurav-nelson/github-action-markdown-link-check ?

> ➜  echidna git:(master) markdown-link-check -q *.md
> 
> FILE: Exercise-1.md
>   [✖] #Targeted-contract
>   [✖] #exercise
> 
>   7 links checked.
> 
>   ERROR: 2 dead links found!
>   [✖] #Targeted-contract → Status: 404
>   [✖] #exercise → Status: 404
> 
> FILE: Exercise-2.md
>   [✖] #exercice
> 
>   8 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] #exercice → Status: 404
> 
> FILE: Exercise-3.md
>   [✖] #exercice
> 
>   11 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] #exercice → Status: 404
> 
> FILE: Exercise-4.md
>   [✖] exercises/token.sol
> 
>   9 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] exercises/token.sol → Status: 400
> 
> FILE: Exercise-5.md
> 
>   15 links checked.
> 
> FILE: Exercise-6.md
> 
>   13 links checked.
> 
> FILE: Exercise-7.md
>   [✖] #exercise
> 
>   6 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] #exercise → Status: 404
> 
> FILE: Exercise-8.md
>   [✖] https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/contracts/the-rewarder/EchidnaRewarder.sol
>   [✖] https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/the-rewarder.yaml
> 
>   13 links checked.
> 
>   ERROR: 2 dead links found!
>   [✖] https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/contracts/the-rewarder/EchidnaRewarder.sol → Status: 404
>   [✖] https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/the-rewarder.yaml → Status: 404
> 
> FILE: README.md
> 
>   29 links checked.
> 
> FILE: assertion-checking.md
> 
>   8 links checked.
> 
> FILE: collecting-a-corpus.md
> 
>   6 links checked.
> 
> FILE: common-testing-approaches.md
> 
>   4 links checked.
> 
> FILE: end-to-end-testing.md
> 
>   5 links checked.
> 
> FILE: filtering-functions.md
> 
>   6 links checked.
> 
> FILE: finding-transactions-with-high-gas-consumption.md
> 
>   12 links checked.
> 
> FILE: frequently_asked_questions.md
>   [✖] https://github.com/crytic/building-secure-contracts/edit/dev-internal-asserts/program-analysis/echidna/testing-modes.md
> 
>   8 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] https://github.com/crytic/building-secure-contracts/edit/dev-internal-asserts/program-analysis/echidna/testing-modes.md → Status: 404
> 
> FILE: fuzzing-introduction.md
> 
>   6 links checked.
> 
> FILE: fuzzing_tips.md
>   [✖] #filtering_inputs
>   [✖] #dealing_with_dynamic_arrays
> 
>   5 links checked.
> 
>   ERROR: 2 dead links found!
>   [✖] #filtering_inputs → Status: 404
>   [✖] #dealing_with_dynamic_arrays → Status: 404
> 
> FILE: hevm-cheats-to-test-permit.md
> 
>   5 links checked.
> 
> FILE: how-to-test-a-property.md
> 
>   7 links checked.
> 
> FILE: property-creation.md
>   [✖] combining-properties
> 
>   6 links checked.
> 
>   ERROR: 1 dead links found!
>   [✖] combining-properties → Status: 400
> 
> FILE: smart-contract-fuzzing-at-scale.md
> 
>   2 links checked.
> 
> FILE: testing-bytecode.md
>   [✖] #generic-proxy-pattern
>   [✖] #summary-testing-bytecode
> 
>   7 links checked.
> 
>   ERROR: 2 dead links found!
>   [✖] #generic-proxy-pattern → Status: 404
>   [✖] #summary-testing-bytecode → Status: 404
> 
> FILE: testing-modes.md
> 
>   5 links checked.
> 
> FILE: using-multi-abi.md
> 
>   7 links checked.

Maybe it would be beneficial to use

**Comment by ggrieco-tob** [comment]
Can you create a separated issue for improving our CI with this tool and tag @elopez there?

**Comment by glarregay-tob** [comment]
> Hints in exercise 8, mentioned [here](https://github.com/crytic/building-secure-contracts/blame/master/program-analysis/echidna/Exercise-8.md#L42-L43), do not exist.
> 
> > * A template is provided in [contracts/the-rewarder/EchidnaRewarder.sol](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/contracts/the-rewarder/EchidnaRewarder.sol)
> > * A config file is provided in [the-rewarder.yaml](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/hints/the-rewarder.yaml)

Those are not in the `hints` branch, but in the `solution` branch:
* [Template](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/solutions/contracts/the-rewarder/EchidnaRewarder.sol)
* [Config file](https://github.com/crytic/damn-vulnerable-defi-echidna/blob/solutions/the-rewarder.yaml)

I'll check the rest of the links and fix them.
