### ISSUE TITLE
Error: Deploying the contract failed 

### ISSUE THREAD

**Issue by darkerego** [crytic/building-secure-contracts#243]
Hi. I have an issue.

Bug: my contracts fails to build when I run 

    $ echidna-test   echidna_test.sol

It does however compile with both brownie, critic-compile, and also slither.  The specific error is:

"echidna-test: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.):" 

Exepected behavior: The contract should compile.  Documentation says I should open an issue. Thanks.

**Comment by elopez** [comment]
Hi! can you share your contract code here? Have you checked if any of the conditions in the error message apply to your contract (usually it's something simple like e.g. your contract constructor reverts, or sends ether to another address, but you've not funded your contract with ether)

**Comment by darkerego** [comment]
Ah, thanks for the quick reply! You are right, it was totally my fault.

**Comment by ggrieco-tob** [comment]
Hi,

Just to clarify: compiling an contract and deploying it without a revert are two different things. Your contract may compile properly, but always fail in the deployment. This is determined during runtime.

**Comment by ggrieco-tob** [comment]
This seems to be fixed
