### ISSUE TITLE
Lack of compiler versions for excercises

### ISSUE THREAD

**Issue by Murat-U-Saglam** [crytic/building-secure-contracts#249]
Just wondering if the absence of ```pragma solidity x.x.x;``` of the solidity files within this area of the [repo](https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna/exercises) is intentional, if so why? Makes it a bit inconvenient when testing and I am not sure if any exercises are dependent on a specific compiler version.

**Comment by 0xPhaze** [comment]
You're right, some exercise depend on a specific version. We are working on a refactor that will these. I will let you know once it's complete.

**Comment by 0xPhaze** [comment]
Completed in 
- https://github.com/crytic/building-secure-contracts/commit/fdeffdbf8966132f38ba9bd084bd9b711a3aa1cb

**Comment by Murat-U-Saglam** [comment]
The changes seem to be for only exercise 1, I'm assuming the latest compiler version for the other exercises is appropriate.

**Comment by 0xPhaze** [comment]
There were additional PRs, I only listed the first. The required versions should be included in all relevant files now.
