### ISSUE TITLE
Add Echidna example to test with Solidity libraries

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/building-secure-contracts#25]

**Comment by montyly** [comment]
Does https://blog.trailofbits.com/2020/08/17/using-echidna-to-test-a-smart-contract-library/ match what you have in mind?

If so, this is fixed with https://github.com/crytic/building-secure-contracts/commit/9b61a29eecfea321bbce187f6e4e1142d36f4094

**Comment by ggrieco-tob** [comment]
Actually, this was fixed in #263
