### ISSUE TITLE
Echidna Exercise 3

### ISSUE THREAD

**Issue by YanhuiJessica** [crytic/building-secure-contracts#296]
[program-analysis/echidna/exercises/exercise3/token.sol#L4](https://github.com/crytic/building-secure-contracts/blob/ee04b2736f81f1b4a7cabc41ee50dca7cbafa023/program-analysis/echidna/exercises/exercise3/token.sol#L4)
```js
/// @notice The issues from exercise 1 and 2 are fixed.
```

Since commit [5c156b9](https://github.com/crytic/building-secure-contracts/commit/5c156b94db30d874ff56d07286327eabb39750f9#diff-990db540f83d6924fceaee71bf4d530f0d40f4f3822a2c983da165ee487b6c6c) changed the solidity version from `^0.8.0` to `^0.5.0`, the issue from exercise 1 becomes unsolved.

**Comment by ggrieco-tob** [comment]
This is a good catch, we will fix them soon.

**Comment by montyly** [comment]
Great catch @YanhuiJessica, thanks. 

We moved back to 0.8 (https://github.com/crytic/building-secure-contracts/pull/308), which fixed this issue ;)
