### ISSUE TITLE
Wrong Contract owner address

### ISSUE THREAD

**Issue by kevinjanada** [crytic/building-secure-contracts#48]
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/how-to-test-a-property.md#initiate-a-contract

There are some specific addresses in Echidna:
- 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 which calls the constructor.
- 0x10000, 0x20000, and 0x00a329C0648769a73afAC7F9381e08fb43DBEA70 which randomly calls the other functions.

When i checked the owner of the contract using an echidna property, the owner of the contract is 0x00a329C0648769a73afAC7F9381e08fb43DBEA70. Not 0x00a329c0648769A73afAc7F9381E08FB43dBEA72.

Should this readme be updated?
Or am i misunderstanding something?

I can create a pull request for this if needed.

**Comment by montyly** [comment]
Thanks @kevinjanada for pointing this out.

@ggrieco-tob: can you take a look a this
