### ISSUE TITLE
Add Echidna tips & tricks

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#54]
- If you fuzz a parameter that is expected to have only some values, use `%`:
```solidity
function f(uint index) public{
   index = `index%2`
   if (index == 0) {...}
   elif (index == 1) {...}
}
```
- To fuzz an arbitrary array length, you can use a push/pop approach (explain why?):
```solidity
uint my_array[]

function push(uint a) public{
  my_array.push(a)
}

function pop() public{
  my_array.pop()
}
```

**Comment by agroce** [comment]
Note that in some cases the push/pop approach will tend to produce smaller arrays than you want.  Omitting pop can be a good idea (indeed, I would wager a decent chunk of the reason swarm testing works is omitting pop).

**Comment by montyly** [comment]
This was added
