### ISSUE TITLE
Add discussion on testing patterns

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#7]
On a high-level, there are two approaches to write properties:
- Targeted: I want to test a specific behavior of a function and want my analyzer to focus only one a particular piece of code
- General: I want X to be always true, no matters the target's context

We need a section that discusses this and highlights the difference with examples.

**Comment by montyly** [comment]
On the same type of topic, we should have some classification with examples on the difference between:
- Defining partially what the target is supposed to do, where we don't necessary expect the behavior of one particular function
- Having a "differential fuzzing" approach, where we compare a targeted function with the expected behavior encoded in a different way

**Comment by montyly** [comment]
Another pattern that I follow often and is worth documenting is to extract parts of the targeted function's code.

For example, if I want to test the arithmetics on a function that has numerous external calls, or configuration-dependent requirements, I tend to write a new function, with only the relevant code.

This has the limitation to not test the actual code, but it has the benefit to allow to test with less "noise", and is faster.

**Comment by ggrieco-tob** [comment]
I believe this is explained in #107, please take a look and let me know if there is some missing pattern

**Comment by ggrieco-tob** [comment]
Done in #107 and a other subsequent PRs.
