### ISSUE TITLE
Misleading documentation about caller addresses

### ISSUE THREAD

**Issue by Silur** [crytic/building-secure-contracts#74]
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/how-to-test-a-property.md#initiate-a-contract claims that:
- `0x00a329c0648769A73afAc7F9381E08FB43dBEA72` is the caller of the constructor
- `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` is the caller of other functions

However, it's just the opposite if you test it with an Ownable contract:

```solidity
contract TestToken is Ownable {
    address echidna_caller = 0x00a329c0648769a73afac7f9381e08fb43dbea70;
    // address echidna_caller = 0x00a329c0648769a73afac7f9381e08fb43dbea72; <- this works
    constructor() public{
      balances[echidna_caller] = 10;
      // owner becomes 0x00a329c0648769a73afac7f9381e08fb43dbea70 here
    }
    function echidna_no_ownership() public view returns (bool) {
      return owner != echidna_caller; //fails
    }
  }
```

**Comment by ggrieco-tob** [comment]
This was fixed.
