### ISSUE TITLE
Assertion testing not working with Echidna 2.0

### ISSUE THREAD

**Issue by RayXpub** [crytic/building-secure-contracts#87]
Hi,

I am trying to run some assertion testing with Echidna 2.0 by using the examples provided in the docs :
```
pragma solidity 0.5.11;

contract Incrementor {
    uint256 private counter = 2**200;

    function inc(uint256 val) public returns (uint256) {
        uint256 tmp = counter;
        counter += val;
        assert(tmp <= counter);
        return (counter - tmp);
    }
}
```
config file :
```
checkAsserts: true
```

When running `echidna-test incrementor.sol --config config.yaml ` I get a the following warning `Warning: unused option: checkAsserts` and the following message `echidna-test: No tests found in ABI`

Why isn't echidna detecting any test ?

**Comment by elopez** [comment]
Hi @RayXpub, thanks for the report! `checkAsserts: true` is no longer a valid option for Echidna 2.0, it has been replaced with `testMode: assertion`. It should work if you use the new option in the config file.

We currently have a pull request open to update things in this repository for Echidna 2.0, #84. I'll leave a comment there to make sure the documentation gets updated to reflect this as well.

**Comment by RayXpub** [comment]
Got it, now it works, thanks !
